bbs/urls.py
#coding:utf-8
from django.conf.urls import patterns, url
from bbs import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='bbs_index')
)

myblog/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'myblog.views.index', name='home'),
    url(r'^index/$', 'myblog.views.index',name='index'),
    url(r'^admin/', include(admin.site.urls)),    
    url(r'^blog/$','myblog.views.blog',name='blog'),
    url(r'^blog/(?P<blog_id>\d+)/$','myblog.views.detail',name='detail'),
    url(r'^bigkola/$','myblog.views.bigkola',name='bigkola'),
    url(r'^empire/$','myblog.views.index',name='empire'),
    url(r'^login/$','myblog.views.login',name='login'),
    url(r'^logout/$', 'myblog.views.logout',),
    url(r'^register/$', 'myblog.views.register'),
    url(r'^test/$','myblog.views.test',name='test'),
    url(r'^search/$', 'myblog.views.search',name="search"),
    url(r'^history/$', 'myblog.views.history',name='history'),
    url(r'^wiki/$', 'myblog.views.wiki',name='wiki'),
    url(r'^message/$', 'myblog.views.message',name='message'),
    url(r'^reply_message/(?P<blog_id>\d+)$', 'myblog.views.post_message',name="post_message"),
    url(r'^reply_a_message/$', 'myblog.views.post_a_message',name='post_a_message'),
    url(r'^email/$', 'myblog.views.email'),
    url(r'^news/', include('news.urls')),
    url(r'^bbs/', include('bbs.urls')),
    url(r'^worldcup/', include('worldcup2014.urls')),
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': 'media'})

)


from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

worldcup2014/urls.py
#coding:utf-8
from django.conf.urls import patterns, url
from worldcup2014 import views

urlpatterns = patterns('',
    url(r'^$', views.index),
    url(r'^all$', views.index_all),
    url(r'^(?P<game_flag>\d+)$', views.index_game),
    url(r'^add$',views.add),
)

worldcup2014/models.py
#coding:utf-8
from django.db import models

# Create your models here.
class Team1(models.Model):
    name = models.CharField(max_length=100,unique=True,
     verbose_name=u'队名')
    website = models.URLField(blank=True,null=True)
    rank = models.CharField(max_length=100,blank=True,null=True)
    def __unicode__(self):
        return self.name

class Team2(models.Model):
    name = models.CharField(max_length=100,unique=True,
     verbose_name=u'队名')
    website = models.URLField(blank=True,null=True)
    rank = models.CharField(max_length=100,blank=True,null=True)
    def __unicode__(self):
        return self.name

class Menu(models.Model):
    text = models.CharField(max_length=300)
    flag = models.IntegerField()
    def __unicode__(self):
        return self.text


class GameDate(models.Model):
    date = models.DateField()
    bio = models.ForeignKey(Menu)
    def __unicode__(self):
        return unicode(self.date)+":"+ self.bio.text


class Game(models.Model):
    team1 = models.ForeignKey(Team1)
    team2 = models.ForeignKey(Team2)
    date = models.ForeignKey(GameDate)
    time = models.TimeField()
    website = models.URLField(blank=True,null=True)
    result = models.CharField(max_length=300,blank=True,null=True)
    def __unicode__(self):
        return (unicode(self.team1)+":"+unicode(self.team2)+
            " "+unicode(self.date)+" "+unicode(self.time))

worldcup2014/views.py
#coding:utf-8
# Create your views here.
from django.shortcuts import render_to_response,render
from django.http import HttpResponse, HttpResponseRedirect,Http404 
from worldcup2014.models import Team1,Game,GameDate,Team2,Menu

teams=u'''澳大利亚,伊朗,日本,韩国,阿尔及利亚,喀麦隆,科特迪瓦,
    加纳,尼日利亚,哥斯达黎加,洪都拉斯,墨西哥,美国,阿根廷,
    巴西,智利,哥伦比亚,厄瓜多尔,乌拉圭,比利时,
    波斯尼亚与赫塞哥维纳,克罗地亚,英格兰,法国,德国,
    希腊,意大利,荷兰,葡萄牙,俄罗斯,西班牙,瑞士'''
team_list = teams.split(",")

def index(request):
    date = GameDate.objects.all()
    menudata = Menu.objects.all()
    return render(request,"worldcup2014.html",locals())
    return HttpResponse("ok")

def add(request):
    try:
        for i in team_list:
            new_team=Team1(
                name = i,
                )
            new_team.save()
        return HttpResponse("oooooook")
    except:
        return HttpResponse("worng")
    return HttpResponse("add")


def index_all(request):
    data = Menu.objects.all()
    return render(request,"worldcup2014_all.html",locals())

def index_game(request,game_flag):
    data = Menu.objects.get(flag=game_flag)
    return render(request,"worldcup2014_game.html",locals())

worldcup2014/templates/worldcup2014.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<title>World Cup</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="Shortcut Icon" href="{{STATIC_URL}}images/logo_net_32.png">
<link href="{{STATIC_URL}}css/worldcup/main.css" rel="stylesheet"> 
<link href="{{STATIC_URL}}css/worldcup/media.css" rel="stylesheet"> 
<link href="{{STATIC_URL}}css/buttons.css" rel="stylesheet"> 
<script src="{{STATIC_URL}}bootstrap/twitter-bootstrap-v2/docs/assets/js/jquery.js"></script>
<style>
@media screen\9,screen\0,(min-width: 781px){
	.main{
		background:url({{STATIC_URL}}images/football1.jpg);
	}
}
</style>
</head>

<body>
<div class="container">
	<div class="navbar"><!--++++++++++++++++导航++++++++++++++++++-->
	  <div class="navbar-cup">
		<div id="world_cup_pic">
		  <a href="/index/">
		    <img src="{{STATIC_URL}}images/ball.png" alt="world cup" height="60px;">
		  </a>
		</div>
		<h3 class="menu_text" id="all_game"><a href="#" class="test">所有比赛</a></h3>
		{%for menu in menudata%}
		<h3 class="menu_text" id="world{{menu.flag}}">
			<a href="{{menu.flag}}" >{{menu.text}}</a><br />
		</h3>

		<script>
		$(document).ready(function(){
		  $("#world{{menu.flag}}").click(function(event){
			$(".content").load("/worldcup/{{menu.flag}}");
			$(".menu_text").css("background-color","");
			$("#world{{menu.flag}}").css("background-color","red");
			event.preventDefault();	
		  });  
		});
		</script>
		{%endfor%}
	  </div>
	  
	  <div class="navbar-about">
	  <ul>
		  <li style="padding-top:0"><h3 style="margin:0;padding-top:0;">
			<a href="#" style="color:#3498DB">友情链接:</a></h3>
		  </li>
		  <li><a href="http://www.zhibo8.cc/">直播8</a></li>
		  <li><a href="http://espn.go.com/">ESPN</a></li>
		  <li><a href="http://www.fifa.com/">FIFA</a></li>
		  <li><a href="http://www.fifa.com/worldcup/">World Cup</a></li>
	  </ul>
	  </div>

	</div> <!--++++++++++++++++导航完++++++++++++++++++-->

	<div class="main"> <!--++++++++++++++++内容区域++++++++++++++++++-->
	  <div class="for-ie">
		<p>您的浏览器版本过低，为了享受更好的体验，请使用
		<a href="https://www.google.com/intl/zh-CN/chrome/browser/" id="for-ie-a">
		<strong>chrome浏览器! （点击下载最新版chrome浏览器）</strong></a>
		</p>
	  </div>		
	  <div class="content">

	  </div>
	</div> <!--++++++++++++++++内容完++++++++++++++++++--> 
</div>

<div class="sidebar-button">
  <a href="#" class="button button-rounded button-flat-caution button-tiny">&nbsp;&nbsp;home&nbsp;&nbsp;</a>
</div>
<div class="sidebar">
  <div class="sidebar-button" id="sidebar-button">
    <a href="#" class="button button-rounded button-flat-primary button-tiny">X</a>
  </div>
  <li><strong>BigKola</strong></li>
  <li class="sidebar-menu"><a href="/index/">Home</a></li>
  <li class="sidebar-menu"><a href="/blog/">Blog</a></li>
  <li class="sidebar-menu"><a href="/news/">News</a></li>
  <li class="sidebar-menu"><a href="/message/">Message</a></li>
  <li class="sidebar-menu"><a href="/email/">E-mail</a></li>
  <li class="sidebar-menu"><a href="/bigkola/">about Kola</a></li>
</div>


<script>
$(document).ready(function(){
  $(".content").load("/worldcup/all");
  $("#all_game").css("background-color","red");
  $("#all_game").click(function(event){
	$(".content").load("/worldcup/all");
	$(".menu_text").css("background-color","");
	$("#all_game").css("background-color","red");	
	event.preventDefault();	
  }); 
  $("#all_game").click(function(event){
	$(".content").load("/worldcup/all");
	event.preventDefault();	
  });   
  $(".for-ie").click(function(event){
	$(".for-ie").hide();
  })
  $("#for-ie-a").click(function(event){
	window.open("https://www.google.com/intl/zh-CN/chrome/browser/","_blank");
	event.preventDefault();	
  })
  $(".sidebar-button").click(function(event){
	$(".sidebar").toggle(300);
  })
  $(".sidebar-menu").click(function(event){
	//window.open($(this).find("a").attr("href"),"_self");
	//event.preventDefault();
  })
});
</script>


</body>
</html>

worldcup2014/templates/worldcup2014_all.html
<script type="text/javascript">
$(document).ready(function(){
	$(".team").hover(function() {
		$(this).find("em").animate({opacity: "show"}, "slow");
	}, function() {
		$(this).find("em").animate({opacity: "hide", top: "-120"}, "fast");
	});
});
</script>
<style>
.world_cup{
	padding-top:10px;
	text-align:center;
}
.world_cup *{
	vertical-align:middle;
}
@media screen\9,\0screen,screen and (min-width:0\0),(min-width: 781px){
	.index_game{
		background-color:#000;
		background: rgba(0, 0, 0, 0.3);
		width:100%;
		padding:20px;
	}
}
@media (min-width: 481px) and (max-width:780px){
	.index_game{
		width:480px;
		margin:auto;
	}
}
@media (max-width:480px){
	.index_game{
		width:300px;
		margin:auto;
	}
}
.index_game *{
	margin:0;
}
.game_day{
	border-bottom:thin dashed #ddd;
	padding-bottom:10px;
}
.index_menu{
	padding-top:10px;
}
.footer{
	width:100%;
	padding-top:50px;
	display: -webkit-flex;
	display: flex;
	-webkit-flex-flow: row wrap;
	flex-flow: row wrap;
}
.footer *{
	color:#eee;
	font-size:90%;
}
.footer a{
	color:#eee;
}
.footer li a{
	color:#eee;
}
.foo-left{
	width:50%;
}
.foo-middle,.foo-right{
	width:25%;
}
.team{
	position: relative;
}
.team em {
	background: rgba(26,188,156,0.6) ;
	width: 280px;
	height: auto;
	position:absolute;
	top: -120px;
	left: -60px;
	padding: 10px 12px 10px;
	font-style: normal;
	z-index: 2;
	display:none;
	border-radius:5px;
}
.team em .triangle{
    width:0; 
    height:0; 
    font-size:0; 
    border-width:15px; 
    border-style:solid; 
    border-color:rgba(26,188,156,0.6) transparent transparent; 
    _border-color:#1ABC9C white white; 
    overflow:hidden; 
    position:absolute; 
    left:60px; 
    bottom:-30px;
}
.team-introduce{
	font-size:90%;
}
</style>
<div class="index_game">
	<h1 class="world_cup">
	  <img src="{{STATIC_URL}}images/trophy.ico" alt="world cup" height="100px;">
	  World Cup
	</h1>
	{%for d in data%}
		<h2 class="index_menu">{{d.text}}</h2>
		  {%for date in d.gamedate_set.all%} 
		    <div class="game_day">
			<h4 class="index_date">{{date.date|date:"Y-m-d"}}</h4>
			  <div>
			  {%for game in date.game_set.all%}				
				{{game.time|date:"H:i"}}&nbsp;&nbsp;&nbsp;&nbsp;
			<span class="team">
			  {{game.team1}}
			  <em>
			    <div class="team-introduce">
				  <p>球队:{{game.team1}}</p>
				  <p>最佳战绩：</p>
				  <p>核心球员：</p>
				  <p><a href="#">点击查看球队详细介绍</a></p>
			    </div><span class="triangle"></span>
			  </em>
			</span> 
			VS 
			<span class="team">
			{{game.team2}}
			  <em>
			    <div class="team-introduce">
				  <p>球队:{{game.team2}}</p>
				  <p>最佳战绩：</p>
				  <p>核心球员：</p>
				  <p><a href="#">点击查看球队详细介绍</a></p>
			    </div><span class="triangle"></span>
			  </em>
			</span>
			&nbsp;&nbsp;
				{%if game.website%}
					<a href="{{game.website}}">直播网站</a>&nbsp;&nbsp;
				{%else%}
				     <a href="#">观看直播</a>&nbsp;&nbsp;
				{%endif%}
				{%if game.result%}
				比赛结果：{{game.result}}
				{%else%}
				未赛
				{%endif%}<br />
			  {%endfor%}
			  </div>
			</div>
		  {%endfor%}
	{%endfor%}
	
	<div class="footer">
		<div class="foo-left">
		©2014 <a href="/index/">BigKola</a>
		</div>
		<div class="foo-middle">
		<strong>Links</strong>
		<li>
		  <a href="/blog/">
			BigKola's Blog
		  </a>
		</li>
		</div>
		<div class="foo-right">
		
		<strong>About Me</strong>
		<li>
		  <a href="/email/">
			E-mail
		  </a>
		</li>
		<li>
		  <a href="https://github.com/imelucifer/">
			Github
		  </a>
		</li>
		<li>
		  <a href="https://plus.google.com/+KolaWang/">
			G+
		  </a>
		</li>
		<li>
		  <a href="http://weibo.com/bigkola/">
			WeiBo
		  </a>	
		</li>
		<li>
		  <a href="http://www.douban.com/people/imelucifer/" >
			DouBan
		  </a>
		</li>
		<li>&nbsp;&nbsp;</li>
		</div>
	</div>
</div>

worldcup2014/templates/worldcup2014_game.html
<script type="text/javascript">
$(document).ready(function(){
	$(".team").hover(function() {
		$(this).find("em").animate({opacity: "show"}, "slow");
	}, function() {
		$(this).find("em").animate({opacity: "hide", top: "-120"}, "fast");
	});
});
</script>
<style>
@media screen\9,\0screen,screen and (min-width:0\0),(min-width: 781px){
.all_games{
		background-color:#000;
		background: rgba(0, 0, 0, 0.3);
		widt:100%;
		padding:20px;
	}
#footer{
		height:0;
		padding:0;
		visibility:hidden;
	}
}
@media (min-width: 481px) and (max-width:780px){
	.all_games{
		width:480px;
		margin:auto;
	}
}
@media (max-width:480px){
	.all_games{
		width:300px;
		margin:auto;
	}
}

.all_games_title{
	text-align:center;
	padding-top:10px;
}
.all_games_title *{
	vertical-align:middle;
}
.all_game_date{
	margin:0;
	padding-top:5px;
}
.all_game_day{
	border-bottom:thin dashed #ddd;
	padding-bottom:20px;
}
.all_game_detail{
	padding-top:2px;
}
.footer{
	width:100%;
	padding-top:50px;
	display: -webkit-flex;
	display: flex;
	-webkit-flex-flow: row wrap;
	flex-flow: row wrap;
}
.footer *{
	color:#eee;
	font-size:90%;
}
.footer a{
	color:#eee;
}
.footer li a{
	color:#eee;
}
.foo-left{
	width:50%;
}
.foo-middle,.foo-right{
	width:25%;
}
.team{
	position: relative;
}
.team em {
	background: #1ABC9C ;
	width: 280px;
	height: auto;
	position:absolute;
	top: -120px;
	left: -60px;
	padding: 10px 12px 10px;
	font-style: normal;
	z-index: 2;
	display:none;
	border-radius:5px;
}
.team em .triangle{
    width:0; 
    height:0; 
    font-size:0; 
    border-width:15px; 
    border-style:solid; 
    border-color:#1ABC9C transparent transparent; 
    _border-color:#1ABC9C white white; 
    overflow:hidden; 
    position:absolute; 
    left:60px; 
    bottom:-30px;
}
.team-introduce{
	font-size:90%;
}
</style>

<div class="all_games">

	<h1 class="all_games_title">
	  <img src="{{STATIC_URL}}images/trophy.ico" alt="world cup" height="100px">
	  {{data.text}}
	</h1>
  
	{%for time in data.gamedate_set.all%}
	  <div class="all_game_day">
		<h4 class="all_game_date">开赛日期：{{time.date|date:"Y年m月d日"}}</h4>
		{%for game in time.game_set.all%}
		  <div class="all_game_detail">
 
			{{game.time|date:"H:i"}}&nbsp;&nbsp;&nbsp;&nbsp;
			<span class="team">
			  {{game.team1}}
			  <em>
			    <div class="team-introduce">
				  <p>球队:{{game.team1}}</p>
				  <p>最佳战绩：</p>
				  <p>核心球员：</p>
				  <p><a href="#">点击查看球队详细介绍</a></p>
			    </div><span class="triangle"></span>
			  </em>
			</span> 
			VS 
			<span class="team">
			{{game.team2}}
			  <em>
			    <div class="team-introduce">
				  <p>球队:{{game.team2}}</p>
				  <p>最佳战绩：</p>
				  <p>核心球员：</p>
				  <p><a href="#">点击查看球队详细介绍</a></p>
			    </div><span class="triangle"></span>
			  </em>
			</span>
			&nbsp;&nbsp;
				{%if game.website%}
					<a href="{{game.website}}">直播网站</a>&nbsp;&nbsp;
				{%else%}
				    <a href="#">观看直播</a>&nbsp;&nbsp;
				{%endif%}
				{%if game.result%}
					比赛结果：{{game.result}}
					{%else%}
					未赛
				{%endif%}<br />
 	
		  </div>
		{%endfor%}
	  </div>	
	{%endfor%}
	<div class="footer" id="footer">
		<div class="foo-left">
		©2014 <a href="/index/">BigKola</a>
		</div>
		<div class="foo-middle">
		<strong>Links</strong>
		<li>
		  <a href="/blog/">
			BigKola's Blog
		  </a>
		</li>
		</div>
		<div class="foo-right">
		
		<strong>About Me</strong>
		<li>
		  <a href="/email/">
			E-mail
		  </a>
		</li>
		<li>
		  <a href="https://github.com/imelucifer/">
			Github
		  </a>
		</li>
		<li>
		  <a href="https://plus.google.com/+KolaWang/">
			G+
		  </a>
		</li>
		<li>
		  <a href="http://weibo.com/bigkola/">
			WeiBo
		  </a>	
		</li>
		<li>
		  <a href="http://www.douban.com/people/imelucifer/" >
			DouBan
		  </a>
		</li>
		<li>&nbsp;&nbsp;</li>
		</div>
	</div>	
</div>