bbs/urls.py
#coding:utf-8
from django.conf.urls import patterns, url
from bbs import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='bbs_index')
)

myblog/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'myblog.views.index', name='home'),
    url(r'^index/$', 'myblog.views.index',name='index'),
    url(r'^admin/', include(admin.site.urls)),    
    url(r'^blog/$','myblog.views.blog',name='blog'),
    url(r'^blog/(?P<blog_id>\d+)/$','myblog.views.detail',name='detail'),
    url(r'^bigkola/$','myblog.views.bigkola',name='bigkola'),
    url(r'^empire/$','myblog.views.index',name='empire'),
    url(r'^login/$','myblog.views.login',name='login'),
    url(r'^logout/$', 'myblog.views.logout',),
    url(r'^register/$', 'myblog.views.register'),
    url(r'^test/$','myblog.views.test',name='test'),
    url(r'^search/$', 'myblog.views.search',name="search"),
    url(r'^history/$', 'myblog.views.history',name='history'),
    url(r'^wiki/$', 'myblog.views.wiki',name='wiki'),
    url(r'^message/$', 'myblog.views.message',name='message'),
    url(r'^reply_message/(?P<blog_id>\d+)$', 'myblog.views.post_message',name="post_message"),
    url(r'^reply_a_message/$', 'myblog.views.post_a_message',name='post_a_message'),
    url(r'^email/$', 'myblog.views.email'),
    url(r'^news/', include('news.urls')),
    url(r'^bbs/', include('bbs.urls')),
    url(r'^worldcup/', include('worldcup2014.urls')),
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': 'media'})

)


from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news/urls.py
#coding:utf-8
from django.conf.urls import patterns, url
from news import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^detail/$',views.detail,name='news_detail'),
    url(r'^(?P<news_id>\d+)/$', views.news_detail),
)

myblog/models.py
#coding:utf-8
from django.db import models
from django.contrib.auth.models import User

class Tag(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name=u'名称')
    count_post = models.IntegerField(default=0, editable=False, verbose_name=u'文章数')
    def __unicode__(self):
        return self.name


class MyBlog(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100,blank=True)
    intro = models.TextField(max_length=500,blank=True)
    content = models.TextField(max_length=99999)
    pub_date = models.DateTimeField(auto_now_add=True)
    website = models.URLField(blank=True)
    count_hit = models.IntegerField(default=0,editable=False, verbose_name=u'点击数')
    tags = models.ManyToManyField(Tag, blank=True, verbose_name=u'标签')
    def __unicode__(self):
        return self.title 


class Message(models.Model):
    text = models.TextField(max_length=1000)
    name = models.CharField(max_length=100,blank=True)
    email = models.EmailField(max_length=100,blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey(MyBlog)
    def __unicode__(self):
        return self.text

class Kola_message(models.Model):
    text = models.TextField(max_length=10000)
    name = models.CharField(max_length=100,blank=True)
    email = models.EmailField(blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    def __unicode__(self):
        return self.text


class Count(models.Model):
    num = models.IntegerField(default=0,verbose_name=u'+1数')
    blog = models.ForeignKey(MyBlog)
    def __unicode__(self):
        return self.num


# 给注册用户添加头像：
class Kola_user(models.Model):
    birthday = models.DateField(null=True,blank=True)
    img = models.ImageField(upload_to='photo',null=True,blank=True)
    big_img = models.ImageField(upload_to='photo',null=True,blank=True)
    small_img = models.ImageField(upload_to='photo',null=True,blank=True)
    phoneNum = models.CharField(max_length=13,null=True,blank=True)
    email = models.EmailField(null=True,blank=True)
    hobbies = models.CharField(max_length=100,null=True,blank=True)
    regTime = models.DateTimeField(null=True,blank=True)
    bio = models.TextField(null = True,blank=True)
    user = models.OneToOneField(User)
    def __unicode__(self):
        return self.bio

news/models.py
#coding:utf-8
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class NewsTag(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name=u'名称')
    count_post = models.IntegerField(default=0, editable=False, verbose_name=u'文章数')
    def __unicode__(self):
        return self.name


class News(models.Model):
    title = models.TextField(max_length=1000)
    text = models.TextField(max_length=4999,null=True,blank=True)
    url = models.URLField(blank=True,null=True)
    dt = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(NewsTag, blank=True, verbose_name=u'标签')
    source = models.CharField(max_length=200,blank=True)
    img = models.ImageField(upload_to='photo',null=True,blank=True)
    def __unicode__(self):
        return self.source+":"+self.title[30]+":"+self.text[:30]

myblog/views.py
#coding:utf-8
from django.shortcuts import render_to_response,render,get_object_or_404  
from django.http import HttpResponse, HttpResponseRedirect,Http404  
from myblog.models import *
from django.core.mail import send_mail
from django.core.paginator import Paginator,InvalidPage,EmptyPage,PageNotAnInteger
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from django.contrib import auth

import PyEmail
import settings
import geetest
#import sae
#from PIL import Image

def index(request):
    '''
    首页
    '''
    return render(request,'index.html')

def blog(request):
    '''
    博客主页
    '''
    mess = []  
    #try:
    messages_list = Kola_message.objects.order_by('-pub_date')[:10]
    blog_list = MyBlog.objects.order_by('-pub_date')

    #总数据列表
    paginator = Paginator(blog_list, 25) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        contacts = paginator.page(1)
    except EmptyPage:
        contacts = paginator.page(paginator.num_pages)

    for i in messages_list:
        #留言板的标题和简介
        if len(i.text)>200:
            mess.append(i.text[:200]+'[...]')
        else:
            mess.append(i.text)
    messages = zip(messages_list,mess) 
    return render(request,'blog.html',locals())

def detail(request,blog_id):
    '''
    详细博文内容
    '''
    try:
        blog = MyBlog.objects.get(pk=blog_id)
    except MyBlog.DoesNotExist:
        raise Http404
    return render(request,'detail.html',locals())

def post_message(request,blog_id):
    '''
    博客留言
    '''
    errors=[]
    flag = ""
    if request.method == "POST":
        if not request.POST.get('message',''):
            errors.append(u'请输入留言内容')
        if not errors:
            mes =Message(
                name=request.POST.get('name',''),
                email= request.POST.get('email',''),
                text= request.POST.get('message',''),
                blog_id=blog_id,
                )
            mes.save()
            flag = u"评论成功。"
    return render_to_response('detail.html',
        locals(),
        context_instance=RequestContext(request))

def post_a_message(request):
    '''
    留言板留言
    '''
    errors=[]
    flag = ""
    if request.method == "POST":
        if not request.POST.get('message',''):
            errors.append(u'请输入留言内容')
        if not errors:
            mes =Kola_message(
                name=request.POST.get('name',''),
                email= request.POST.get('email',''),
                text= request.POST.get('message',''),
                )
            mes.save()
            flag = u"留言成功提交。"
            try:
                title = "message:"+request.POST.get('name','').encode('utf-8')+';'+request.POST.get('email','').encode('utf-8')
                content = request.POST.get('message','').encode('utf-8')
                PyEmail.SendMail('kola@bigkola.info',title,content) 
            except:
                pass

    return HttpResponseRedirect("/message/")

def bigkola(request):
    '''
    联系bigkola
    '''
    return render(request,'bigkola.html')

def message(request):
    '''
    留言板
    '''
    mes = Kola_message.objects.order_by('-pub_date')[:100]
    errors=[]
    flag = ""
    if request.method == "POST":
        #验证部分代码 +++++++++++++++++++++++++++++++++++++++++++++++
        challenge = request.POST.get('geetest_challenge')
        validate = request.POST.get('geetest_validate')
        seccode = request.POST.get('geetest_seccode')
        gt = geetest.geetest('geetest_KEY')
        if not gt.geetest_validate(challenge, validate, seccode):
            errors.append(u'验证未通过，请先通过验证')       
        #  ——————————————————————————————————————————————————————————
            
        if not request.POST.get('message',''):
            errors.append(u'请输入留言内容')
        if not errors:
            message =Kola_message(
                name=request.POST.get('name',''),
                email= request.POST.get('email',''),
                text= request.POST.get('message',''),
                )
            message.save()
            flag = u"留言成功提交。"
            try:
                title = "message:"+request.POST.get('name','').encode('utf-8')+';'+request.POST.get('email','').encode('utf-8')
                content = request.POST.get('message','').encode('utf-8')
                PyEmail.SendMail('kola@bigkola.info',title,content) 
            except:
                pass
    return render(request,'message.html',locals())

def empire(request):
    return  HttpResponse(u'暂未开通....')

def history(request):
    '''
    编年史板块
    '''
    return render(request,'history.html')

def wiki(request):
    '''
    百科全书板块
    '''
    return render(request,'wiki.html')

def search(request):
    errors = []
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            errors.append(u'请填写查询内容！')
        elif len(q)>20:
            errors.append(u'填写内容必须小于20字！')
        else:  
            blog = MyBlog.objects.filter(title__icontains=q)
            return render_to_response('search.html',
                {'blog':blog,'q':q},context_instance=RequestContext(request))
    return render_to_response('search.html',{'errors':errors},
        context_instance=RequestContext(request))

def email(request):
    errors=[]
    flag = ""
    if request.method == "POST":
        if not request.POST.get('name',''):
            errors.append(u'请输入你的名字')
        if not request.POST.get('email',''):
            errors.append(u'请输入您的邮箱地址')
        if not request.POST.get('message',''):
            errors.append(u'请输入邮件内容')
        if not errors: 
            try:
                title = 'bigkola'+':'+request.POST.get('name','').encode('utf-8') +';'+request.POST.get('email','').encode('utf-8')
                content = request.POST.get('message','').encode('utf-8')
                PyEmail.SendMail('kola@bigkola.info',title,content)         
                flag = u"邮件发送成功。"
            except:
                flag =u'邮件发送失败'
    return render_to_response('email.html',locals(),context_instance=RequestContext(request))


def test(request):
    pass

#登录视图:
#@csrf_exempt
def login(request):
    errors = []
    register_flag = False
    if request.method == "POST":
        if not request.POST.get('username',''):
            errors.append(u"请输入用户名")
        if not request.POST.get('password',''):
            errors.append(u"请输入密码")
        else:
            name = request.POST.get('username','')
            password = request.POST.get('password','')
            user = auth.authenticate(username=name,
                password=password)
            if user is not None and user.is_active:
                auth.login(request,user)
                return HttpResponseRedirect("/index/")
            else:
                errors.append(u'登录失败，请重试')
    #response = render(request,'login.html',locals())
    response = render_to_response('login.html',
        {'errors':errors,},
        context_instance=RequestContext(request))
    return render(request,'login.html',locals())

def logout(request):
    if request.user.is_authenticated():
        auth.logout(request)
        return render(request,"logout.html",{})
    else:
#        return render(request,"logout.html",{})
        return HttpResponseRedirect("/index/") 



#注册视图
from django.contrib.auth.models import User

@csrf_exempt
def register(request):
    errors=[]
    if request.method == 'POST':
        name = request.POST.get('username','')
        password1 = request.POST.get('password1','')
        password2 = request.POST.get('password2','')
        if len(name)<3:
            errors.append(u'用户名长度必须大于4个字符')
        elif len(password1)<6:
            errors.append(u'密码长度必须大于6个字符')
        elif password1 != password2 :
            errors.append(u'两次输入密码必须相同')
        else:
            try:
                user = User.objects.get(username=name)
                errors.append(u'用户名已被注册')
                return render(request,'register.html',{'errors':errors})
            except User.DoesNotExist:    
                user = User.objects.create_user(
                    username = name,
                    password = password1,
                    )
                register_flag = True
                return render(request,'login.html',{'register_flag':register_flag})
        return render(request,'register.html',{'errors':errors})
    else:
        return render(request,'register.html')

news/views.py
#coding:utf-8
from django.shortcuts import render_to_response,render
from django.http import HttpResponse, HttpResponseRedirect,Http404  
from news.models import News,NewsTag
from django.core.paginator import Paginator,InvalidPage,EmptyPage,PageNotAnInteger
import random

#导入geetest验证包
import geetest

def index(request):
    login_flag = False
    kola_name = ''
    errors = []
    flag = ''
    news_list = []
    if "login_flag" in request.session:
        login_flag = True
        kola_name = request.session['name']
    news = News.objects.order_by("-dt")
    if request.method == "POST":
        
        # 使用geetest验证码验证 +++++++++++++++++++++++++++++++++++++
        challenge = request.POST.get('geetest_challenge')
        validate = request.POST.get('geetest_validate')
        seccode = request.POST.get('geetest_seccode')
        gt = geetest.geetest('geetest_KEY')      
        if not gt.geetest_validate(challenge, validate, seccode):
            errors.append(u'验证未通过，请先通过验证')  
        # ———————————————————————————————————————————————————————————
        
        if len(request.POST.get('news',''))<70:
            errors.append(u'提交内容长度必须大于70字.')
        if len(request.POST.get('news',''))>1000:
            errors.append(u"提交内容长度过长,不超过1000个字.")
        if not errors:
            new_news =News(
                title=request.POST.get('news',''),
                source=u"匿名新闻",
                )
            new_news.save()
            request.session["news_flag"] = True
            flag = u"匿名新闻提交成功。"
            return HttpResponseRedirect('/news/')

    paginator = Paginator(news, 40) # Show 25 contacts per page
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        contacts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        contacts = paginator.page(paginator.num_pages)    
    return render(request,'news_index.html',locals())


def detail(request):
    #news = News.objects.get(pk=news_id)
    return HttpResponse("ok")
    #return render(request,'news',locals())

def news_detail(request,news_id):
    news = News.objects.get(pk=news_id)
    return render(request,'news.txt',locals())

myblog/templates/4XX.html
<!DOCTYPE html>
<html lang="en-US"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="UTF-8">
    <title>页面未找到</title>
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/cmstop-error.css" media="all">
</head>
<body class="body-bg">
<div class="main">
    <p class="title">非常抱歉，您要查看的页面没有办法找到</p>
    <a href="/index/" class="btn">返回网站首页</a>
</div>

</body></html>

myblog/templates/blog.html
{% extends "base.html" %}
{% block title %}BigKola Blog{%endblock%}
{% block content %}


 
<style>
.span7,.well{	
	background-color:#fff;
	border-radius:5px;
	border-top:thin solid #dddddd;
	border-bottom:thin solid #dddddd;
}
h2{
	text-shadow: 2px 2px 2px #ccc;
	font-family:"Microsoft YaHei" sans-serif;
}
.theblog{
	border-top:thin solid #dddddd;
	padding:5px 10px;
}
.title{color:#336699}


.thewhite{
	margin:10px;
	border-bottom:thin solid #dddddd;
}
.sub{
	margin-right:15px;
	text-align:right;
}

.the_message{
	padding-top:5px;
	border-top:thin solid #dddddd;
}
#message_time{
	text-align:right;
}
#message_time a{
	font-size:10px;
}
.mainblog{
	margin-top:60px;
}
.main_8{
	background-color:#fff;
	border-radius:5px;
}
.full_text{
	margin-bottom:10px;
	text-align:right;
}
.full_text a:hover{
	text-decoration:none;
}
.the_message_text{
	table-layout:fixed; 
	word-break: break-all;
	overflow:hidden; 
}
#content{
	word-break: break-all;
}

.pagination{
	padding:20px;
}
.geetest-test{
	position: relative;
	margin-top: 10px;
	float: right;
}
.sub{
	padding:15px 5px 5px 5px;
	border-top:thin solid #dddddd;
	text-align:right;
}
.the_message{
	padding:10px 20px 5px 10px;
	border-top:thin solid #dddddd;
}
.message_text{
	width:430px;
}
.message_title{
	text-align: center;
	padding-bottom: 20px;
	padding-top: 20px;
	border-top:thin solid #dddddd;
}

</style>

<div class="container mainblog">
  <div class="row">
    <div class="span8 main_8"><!--start blog-->
	  <div class="blog_img">
	     <img src="{{STATIC_URL}}images/blog.png"> 
	  </div>	
	  {% if blog_list %} 
		{% for blog in contacts %}
			<div class="theblog">
			  <ul class="nav nav-list">
			    <li class="nav-header">
				 <div>
  				  <h2>
				    <a href="/blog/{{blog.id}}" class="title">
				      {{blog.title}} 
				    </a>
				  </h2>	 
				 </div> 
				  {%if blog.author%}
				  <p>
					<strong>&nbsp;<a href="#">•&nbsp;via:{{blog.author}}</a></strong> 
					&nbsp;&nbsp;|&nbsp;&nbsp; <a href="#">{{blog.pub_date|date:"Y年m月d日"}}</a>&nbsp;&nbsp;|&nbsp;&nbsp;<span><a href="#"> {{blog.message_set.all|length}}评论</a></span> 
				  </p>	
				  {%else%}
				  <p>
				    <strong>&nbsp;<a href="#">•&nbsp;via:admin</a></strong>
					&nbsp;&nbsp;|&nbsp;&nbsp; <a href="#">{{blog.pub_date|date:"Y年m月d日"}}</a>&nbsp;&nbsp;|&nbsp;&nbsp;<span><a href="#"> {{blog.message_set.all|length}}评论</a></span>
				  </p>	
				  {%endif%}
				</li>
				<p id="content">       {{blog.intro|safe}}  <br>	</p>
				
				 
				  <div class="full_text">
				    <a href="/blog/{{blog.id}}" id="full_text_{{blog.id}}"> 阅读全文 </a>
					<style>
					#full_text_{{blog.id}}{
						padding:5px 10px;
						background-color:#f3f3f3;
					}
					</style>
					<script>
					$(document).ready(function(){
					  $("#full_text_{{blog.id}}").mouseover(function(){
						$("#full_text_{{blog.id}}").css("background-color","#0033FF");
						$("#full_text_{{blog.id}}").css("color","white");
					  });
					  $("#full_text_{{blog.id}}").mouseout(function(){
						$("#full_text_{{blog.id}}").css("background-color","#f3f3f3");
						$("#full_text_{{blog.id}}").css("color","#0088cc");
					  });
					});
					</script>
				  </div>   
	 
				
			  </ul>
			</div>
		{% endfor %}
	  {%else%}
		<p>No Blog</p>
	  {%endif%}  
	  
	  
	<style>
	.page{
	margin:5px auto 25px 20px;
	}
	</style>
      <div class="page">
        {% if contacts.has_previous %}
		
            <a href="?page={{ contacts.previous_page_number }}" class="has_previous">上一页</a>
			<span class="has_center">
            &nbsp;| &nbsp; <strong>{{ contacts.number }} / {{ contacts.paginator.num_pages }}</strong>
			</span>
			{% if contacts.has_next %}
			 &nbsp;| &nbsp;<a  class="has_next" href="?page={{ contacts.next_page_number }}">下一页</a>
			{% endif %}
		{%else%}
			{% if contacts.has_next %}
			    <a href="?page={{ contacts.next_page_number }}">→查看更多</a>
			{%else%}
			        <span>
            <a href="#"> {{ contacts.number }} / 共{{ contacts.paginator.num_pages }}页</a>
					</span>
			{% endif %}
		{% endif %}
      </div>	

    <div class="message">
	  <div class="message_title">
		<h3>快速留言：</h3>
	  </div>
		<form class="message form-horizontal " id="message_form" action=/message/ method="post">
				{%csrf_token%}
				<fieldset>
				  
				  <div class="control-group">
					<label class="control-label" for="input01">姓名（可选）：</label>
					<div class="controls">
					  <input type="text" class="input-xlarge message_text" id="input01" placeholder="Type Name…" name="name">
					</div>
				  </div>
				  
				  <div class="control-group">
					<label class="control-label" for="input01">邮箱（可选）：</label>
					<div class="controls">
						<input type="text" class="input-xlarge message_text"  placeholder="Type Email…" name="email">
					 
						<div class="alert alert-info">
						  <a class="close" data-dismiss="alert">×</a>
						  {%if flag%}
						  {{flag}}
						  {%else%}
						  <strong>给帝国留言：</strong>
						  {%endif%}
						</div> 
						
						{% if errors%}
						{% for error in errors %}
						<div class="alert alert-error">
						  <a class="close" data-dismiss="alert">×</a>
						  <strong>警告!</strong> {{error}}
						</div>
						{%endfor%}
						
						{%endif%}
						</div>
				  </div>		  
				  
				  
				  <div class="control-group">
					<label class="control-label" for="textarea">留言：</label>
					<div class="controls">
					  <textarea class="message_text" id="textarea" rows="10" cols="50" 
						maxlength="10000"
						placeholder="Type Message…" name="message"></textarea>
					</div>
					  <div class="geetest-test">
					  <script type="text/javascript" src="http://api.geetest.com/get.php?gt=a5090d65309f03a46900aceb02eb687e"></script>
					  </div>					
				  </div>
				  <div class="sub">
					<button type="submit" class="button button-rounded button-flat-highlight" id="message_button">提交留言</button>
				  </div>
				</fieldset>
		</form>
    </div><!--end message-->

	</div><!--end blog-->
	
	<div class="span4">
		<div class="well sidebar-nav">
				<ul class="nav nav-list">
				  <li class="nav-header">帝国友情链接：</li>
				  <li class="active">
				    <a href="http://wickedonna2.tumblr.com/">
					老卢的Tumblr
					</a>
				  </li>
				  <li>
				    <a href="http://t66y.com/">
					1024
					</a>
				  </li>
				  <li>
				    <a href="https://thepiratebay.se/">
					海盗湾
					</a>
				  </li>
				  <li>
				    <a href="http://weekly.manong.io/">
					码农周刊
					</a>
				  </li>
				  <li>
					<a href="https://www.python.org/">
					Python
					</a>
				  </li>
				  <li>
				    <a href="http://www.bootcss.com/">
					Bootstrap
					</a>
				  </li>
				  <li>
				    <a href="http://www.google.com/ncr">
					Google
					</a>
				  </li>
			   </ul>
		</div><!--/.well -->
	<!--=======SNS================================-->	
			   
		<div class="well">

			 <ul class="nav nav-list">
			   <li class="nav-header">分享到SNS：</li>
			 <li>
				<div class="go">	   
				<!-- 将此标记放置在你希望显示+1 按钮的位置。 -->
				  <div class="g-plusone" data-annotation="inline" data-width="300"></div>

				<!-- 将此标记放置在最后一个 +1 按钮 标记之后。 -->
				  <script type="text/javascript">
					  window.___gcfg = {lang: 'zh-CN'};

					  (function() {
						var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
						po.src = 'https://apis.google.com/js/platform.js';
						var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
					  })();
				  </script>
				</div><!-- end google +1。 -->
			 </li>

			<li>	
				<div class="sina">
				  <html xmlns:wb=“http://open.weibo.com/wb”>
				  <script src="http://tjs.sjs.sinajs.cn/open/api/js/wb.js" type="text/javascript" charset="utf-8">
				  </script>
				  <wb:share-button appkey="3n3Yax" addition="number" type="button" 
				  ralateUid="3874142518" default_text="欢迎光临帝国！"></wb:share-button>
				</div><!-- end sina 。 -->
			</li>	

			<li class="thewhite"></li>

			<li class="nav-header">添加BigKola的微信：</li>	
			<li id="myweixin">
				<img src="{{STATIC_URL}}images/weixin.png" alt="我的微信" />
			</li>
				
			</ul>	
		</div><!-- end SNS分享。 -->



		<div class="well">
		  <ul class="nav nav-list">
			 <li class="nav-header">帝国最新留言：</li>
			{%if messages%}
			{% for message,text in messages %}
			<li>
			  <div class="the_message">
			    <p>
					{% if message.name%}
						帝国公民：<a href="#">{{message.name}}</a>留言说：
					{% else %}
						<a>匿名</a>留言：
					{%endif%}
				</p>
				{%if text%}
					<p class="the_message_text">{{text|safe}}<p>
				{% else %}
					<p>......</p>
				{%endif%}
				
			  <p id="message_time">
				<a href=/message/>{{message.pub_date|date:"Y年m月d日 H时i分"}}</a>
			  </p>

			  </div>
			</li>
		{% endfor %}
		{%else%}
		  <strong>暂时还无人留言.</strong>
		{%endif%}
		</div>

		

	</div><!-- end span4。 -->
  </div><!-- end row。 -->
</div><!-- end container。 -->




{%endblock%}

myblog/templates/history.html
{% extends "base.html" %}
{% block title %}BigKola History{%endblock%}
{% block content %}
<style>
.history{margin-top:50px ;height:2000px;}
</style>
<div class="history">
  <h1>帝国编年史正在撰写中。。。。</h1>
</div>
{%endblock%}

myblog/templates/search.html
{% extends "base.html" %}
{% block title %}给Kola发送Email{%endblock%}
{% block content %}
<style>
.my_search{
	width:500px;
	height:1500px;
	margin:150px auto auto auto;
}
</style>
<div class="container my_search">
	{% if errors %}
		<ul>
			{% for error in errors %}
			<li>
				<div class="alert alert-info">
					<a class="close" data-dismiss="alert">×</a>
					{{error}}	  
				</div>
			</li>		
			{% endfor %}
		</ul>
	{% endif %}
	<form action="" method="get">
		<input type="text" name='q' />		
		<input type="submit" value="Search" />
	</form>

{% if not errors %}
<p>查询: <strong>{{q}}</strong></p>

{% if blog %}
	<p>找到 {{blog|length}} 篇博文。</p>
	<ul>
		{% for b in blog %}
		<a href="/blog/{{b.id}}"><li>{{b.title}}</li></a>
		{% endfor %}
	</ul>
{% else %}

	<p style="color: red;"> 没有找到包含“{{q}}”的博文。 </p>
	
{%endif%}{%endif%}



</div>
{%endblock%}

myblog/templates/wiki.html
{% extends "base.html" %}
{% block title %}BigKola Wiki{%endblock%}
{% block content %}
<style>
.history{margin-top:50px ;height:2000px;}
</style>
<div class="history">
  <h1>帝国百科全书正在撰写中。。。。</h1>
</div>
{%endblock%}